name: Publish

on:
  push:
    branches:
      - master

jobs:
  release:
    name: npm publish / GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare configuration
        run: cp -f .releaserc.ci.json .releaserc.json
      - name: Install
        env:
          CI: true
        run: npm ci
      - name: Semantic Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
